apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice10
  labels:
    app: configservice10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice10
  template:
    metadata:
      labels:
        app: configservice10
    spec:
      containers:
        - name: configservice10
          image: 636090713215.dkr.ecr.us-east-1.amazonaws.com/configservice10:v1.23
          imagePullPolicy: Always
          ports:
            - containerPort: 8080